export const EVENTS = {
  mousedown: 'mousedown',
  mouseup: 'mouseup',
  mousemove: 'mousemove',
  mousewheel: 'mousewheel',
  keydown: 'keydown',
  keyup: 'keyup',
  contextmenu: 'contextmenu',
  // click: "click",
  // dblclick: "dblclick",
  // change: "change",
  // select: "select",
  // submit: "submit",
  // load: "load",
  // unload: "unload",
};

export const MARCROTYPE = {
  keydown: 'key down',
  keyup: 'key up',
  mousedown: 'mouse down',
  mouseup: 'mouse up',
  mousemove: 'mouse move',
  mousewheel: 'mouse wheel',
  contextmenu: 'mouse context',
  dblclick: 'dblclick',
  change: 'change',
  select: 'select',
  submit: 'submit',
  load: 'load',
  unload: 'unload',
  screenshot: 'screenshot',
};

export const KEYTYPE = {
  // : "NULL",
  Cancel: 'CANCEL',
  Help: 'HELP',
  Backspace: 'BACK_SPACE',
  Tab: 'TAB',
  Clear: 'CLEAR',
  // : "RETURN",
  Enter: 'ENTER',
  ShiftRight: 'SHIFT',
  ShiftLeft: 'LEFT_SHIFT',
  ControlRight: 'CONTROL',
  ControlLeft: 'LEFT_CONTROL',
  AltRight: 'ALT',
  AltLeft: 'LEFT_ALT',
  // : "PAUSE",
  Escape: 'ESCAPE',
  Space: 'SPACE',
  PageUp: 'PAGE_UP',
  PageDown: 'PAGE_DOWN',
  // : "END",
  Home: 'HOME',
  // : "LEFT",
  ArrowLeft: 'ARROW_LEFT',
  // : 'UP',
  ArrowUp: 'ARROW_UP',
  // : "RIGHT",
  ArrowRight: 'ARROW_RIGHT',
  // : "DOWN",
  ArrowDown: 'ARROW_DOWN',
  // : 'INSERT',
  Delete: 'DELETE',
  // : 'SEMICOLON',
  // : "EQUALS",
  Numpad0: 'NUMPAD0',
  Numpad1: 'NUMPAD1',
  Numpad2: 'NUMPAD2',
  Numpad3: 'NUMPAD3',
  Numpad4: 'NUMPAD4',
  Numpad5: 'NUMPAD5',
  Numpad6: 'NUMPAD6',
  Numpad7: 'NUMPAD7',
  Numpad8: 'NUMPAD8',
  Numpad9: 'NUMPAD9',
  NumpadMultiply: 'MULTIPLY',
  NumpadAdd: 'ADD',
  // : "SEPARATOR",
  NumpadSubtract: 'SUBTRACT',
  // : 'DECIMAL',
  NumpadDivide: 'DIVIDE',
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  F6: 'F6',
  F7: 'F7',
  F8: 'F8',
  F9: 'F9',
  F10: 'F10',
  F11: 'F11',
  F12: 'F12',
  MetaLeft: 'META',
  MetaRight: 'META',
  // : 'COMMAND',
  // : 'ZENKAKU_HANKAKU'
  Digit0: '0',
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  KeyA: 'a',
  KeyB: 'b',
  KeyC: 'c',
  KeyD: 'd',
  KeyE: 'e',
  KeyF: 'f',
  KeyG: 'g',
  KeyH: 'h',
  KeyI: 'i',
  KeyJ: 'j',
  KeyK: 'k',
  KeyL: 'l',
  KeyM: 'm',
  KeyN: 'n',
  KeyO: 'o',
  KeyP: 'p',
  KeyQ: 'q',
  KeyR: 'r',
  KeyS: 's',
  KeyT: 't',
  KeyU: 'u',
  KeyV: 'v',
  KeyW: 'w',
  KeyX: 'x',
  KeyY: 'y',
  KeyZ: 'z',
  BracketLeft: 'BracketLeft',
  BracketRight: 'BracketRight',
  Minus: 'Minus',
  Equal: 'Equal',
  Semicolon: 'Semicolon',
  Quote: 'Quote',
  Comma: 'Comma',
  Period: 'Period',
  Slash: 'Slash',
  Backslash: 'Backslash',
};
